trigger:
- master

jobs:
- job: Build
  strategy:
    matrix:
      windows:
        imageName: 'windows-latest'
      linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
  pool:
    vmImage: $(imageName)
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
    displayName: 'Build and test on $(imageName)'

- job: Benchmark
  strategy:
    matrix:
      windows:
        imageName: 'windows-latest'
      linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
  pool:
    vmImage: $(imageName)
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/*.json'
    displayName: 'Build and run benchmarks on $(imageName)'