trigger:
  - master

jobs:
  - job: Build
    strategy:
      matrix:
        windows:
          vmImage: 'windows-latest'
        linux:
          vmImage: 'ubuntu-latest'
        macOS:
          vmImage: 'macOS-latest'
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'clean build'
  - job: Benchmark
    strategy:
      matrix:
        windows:
          vmImage: 'windows-latest'
        linux:
          vmImage: 'ubuntu-latest'
        macOS:
          vmImage: 'macOS-latest'
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/*.json'
          tasks: 'clean build benchmark'
mostra il nome di  ogni task 